info:
    description: "SidgsLuxuryHomesIdentityHeadless REST API"
    license:
        name: "Apache 2.0"
        url: "http://www.apache.org/licenses/LICENSE-2.0.html"
    title: "SidgsLuxuryHomesIdentityHeadless"
    version: v1.0
openapi: 3.0.1
components:
  schemas:
    Register:
      description: https://www.schema.org/Register
      properties:
        firstName:
          type: string
        lastName:
          type: string
        emailAddress:
          type: string
        phoneNumber:
          type: string
        dateOfBirth:
          type: string
        tAndC:
          type: boolean
      type: object
    HospStatus:
      description: https://www.schema.org/HospStatus
      properties:
        status:
          type: string
        message:
          type: string
      type: object
paths:
  /registration:
    post:
      operationId: postRegistration
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Register'
          application/xml:
            schema:
              $ref: '#/components/schemas/Register'
      responses:
        default:
          description: 'Registration API'
          content:
            application/json:
              schema:
                type: string
            application/xml:
              schema:
                type: string
      tags:
        - SignUp
  /forgotPassword:
    post:
      operationId: postForgotPassword
      requestBody:
        content:
          application/json:
            schema:
              type: string
          application/xml:
            schema:
              type: string
      responses:
        default:
          description: 'Forgot Password API'
          content:
            application/json:
              schema:
                type: string
            application/xml:
              schema:
                type: string
      tags:
        - ForgotPassword