info:
    description: "SidgsLuxuryHomesPropertyHostingHeadless REST API"
    license:
        name: "Apache 2.0"
        url: "http://www.apache.org/licenses/LICENSE-2.0.html"
    title: "SidgsLuxuryHomesPropertyHostingHeadless"
    version: v1.0
openapi: 3.0.1
components:
  schemas:
    Feature:
      description: https://www.schema.org/Feature
      properties:
        id:
          type: string
        categoryId:
          type: integer
          format: int64
        groupId:
          type: integer
          format: int64
        name:
          type: string
        primaryType:
          type: string
        subType:
          type: string
        description:
          type: string
        imageIcon:
          type: string
      type: object
    Features:
      description: https://www.schema.org/Features
      properties:
        features:
          type: array
          items:
            $ref: '#/components/schemas/Feature'
      type: object
    HostProperty:
      description: https://www.schema.org/HostProperty
      properties:
        title:
          type: string
        description:
          type: string
        coordinates:
          type: string
        address:
          type: string
        guests:
          type: integer
          format: int64
        bedrooms:
          type: integer
          format: int64
        beds:
          type: integer
          format: int64
        bathrooms:
          type: integer
          format: int64
        images:
          type: string
        availableFrom:
          type: string
      type: object
    PropertyStatus:
      description: https://www.schema.org/PropertyStatus
      properties:
        status:
          type: string
        message:
          type: string
      type: object
paths:
  /propertyTypes:
    get:
      operationId: getPropertyTypes
      responses:
        default:
          description: 'Get Property Types API'
          content:
            application/json:
              schema:
                type: string
            application/xml:
              schema:
                type: string
      tags:
        - Feature
  /amenities:
    get:
      operationId: getAmenities
      responses:
        default:
          description: 'Get Amenities API'
          content:
            application/json:
              schema:
                type: string
            application/xml:
              schema:
                type: string
      tags:
        - Feature
  /property:
    post:
      operationId: postProperty
      requestBody:
        content:
          multipart/form-data:
            files:
              type: array
              items:
                type: string
                format: binary
            schema:
              $ref: '#/components/schemas/HostProperty'
      responses:
        default:
          description: 'Create Property API'
          content:
            application/json:
              schema:
                type: string
            application/xml:
              schema:
                type: string
      tags:
        - HostProperty